project_name: cmake_smoke
workspace: ../../tests/fixtures/cmake-smoke
build_dir: build
generator: Ninja
configure_args:
  - -DCMAKE_C_COMPILER=D:/STM32CubeCLT_1.19.0/GNU-tools-for-STM32/bin/arm-none-eabi-gcc.exe
  - -DCMAKE_SYSTEM_NAME=Generic
  - -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY
